### ISSUE TITLE
^[[K escape code is displayed with color output is piped from programs like ack

### ISSUE THREAD

**Issue by dmmalam** [FauxFaux/most-pager#1]
I'm not sure if this the official place to report bugs??

When color output is piped into `most`, like from `ack` or `ag`, the escape code `^[[K` is displayed at the end of every line. This doesn't happen with `less` so seems like a bug.

**Comment by reitzig** [comment]
From the creator of most via private communication:

> Please try the latest version on <https://jedsoft.org/snapshots/>.  It
addresses the issue.   Thanks, --John
