### ISSUE TITLE
`configure` expects slang.h file

### ISSUE THREAD

**Issue by jasper-zanjani** [FauxFaux/most-pager#2]
Installing on a brand-new Fedora 31 install, running `configure` produced the following error:
```
checking for the slang library and header files ... no
configure: error: unable to find the slang library and header file slang.h
```
I do have version 2.3.2 of the S-Lang library installed.

**Comment by FauxFaux** [comment]
You probably want a version of this library which isn't nine years out of date.

I'm going to archive this fork.
